### ISSUE TITLE
Consumer grant checks could benefit from an inverted method

### ISSUE THREAD

**Issue by ladydascalie** [LUSHDigital/core#68]
At the moment with the current API for consumers, the following code ends up happening all over the place:

```
if !consumer.HasAnyGrant(admin, create) {
	return UnauthorisedError{}
}
```

I would suggest that something like the following would be a nice-to-have addition, which would help prevent the innevitable missing `!` issue.

```
if consumer.MissesAnyGrants(admin, create) {
	return UnauthorisedError{}
}
```

**Comment by zeevallin** [comment]
Closed by #69
